<?php
$lang = 	array("EN",
			"FEEDS MONITOR",
			"Feed Types",
			"Social",
			"Websites",
			"RSS",
			"Forums",
			"Monitored feeds & sources",
			"Last feed updated",
			"Scheduler",
			"Add source",
			"Save view",
			"Load view",
			"Export to CSV",
			"Feeds & Collected Data",
			"Top 10 Sources over Time",
			"Devices",
			"Sentiment",
			"Languages",
			"Social Networks",
			"Add a source",
			"Close",
			"Feed Type",
			"Feed source",
			"Source name",
			"Feed URL",
			"Feed schedule",
			"Hourly",
			"Daily",
			"Weekly",
			"View name",
			"Edit the source",
			"Are you sure you want to delete this?",
			"GO",
			"Bulk Upload",
			"Choose File",
			"No file chosen",
			"Upload feeds",
			"Show log",
			"Monday",
			"Tuesday",
			"Wednesday",
			"Thursday",
			"Friday",
			"Saturday",
			"Sunday",
			"Schedule day",
			"Schedule hour"
			);
?>			
