//language arrays
var enlang = 	["EN",
			"FEEDS MONITOR",
			"Feed Types",
			"Social",
			"Websites",
			"RSS",
			"Forums",
			"Monitored feeds & sources",
			"Last feed updated",
			"Scheduler",
			"Add source",
			"Save view",
			"Load view",
			"Export to CSV",
			"Feeds & Collected Data",
			"Top 10 Sources over Time",
			"Devices",
			"Sentiment",
			"Languages",
			"Social Networks",
			"Add a source",
			"Close",
			"Feed Type",
			"Feed source",
			"Source name",
			"Feed URL",
			"Feed schedule",
			"Hourly",
			"Daily",
			"Weekly",
			"View name",
			"Edit the source",
			"Are you sure you want to delete this?",
			"GO",
			"Bulk Upload",
			"Choose File",
			"No file chosen",
			"Upload feeds",
			"Show log",
			"Monday",
			"Tuesday",
			"Wednesday",
			"Thursday",
			"Friday",
			"Saturday",
			"Sunday",
			"Schedule day",
			"Schedule hour"
];

var frlang =   ["FR",
			"SURVEILLER LES FLUX",
			"De Flux",
			"Social",
			"Sites Internet",
			"RSS",
			"Forums",
			"Flux et sources surveillés",
			"Dernière mise à jour",
			"Planificateur",
			"Ajouter une source",
			"Sauvegarder la vue",
			"Obtenir la vue",
			"Exportation en fichier CSV",
			"Flux et données collectées",
			"10 PRINCIPALES SOURCES AU FIL DU TEMPS",
			"DISPOSITIF",
			"SENTIMENT",
			"LANGUES",
			"RÉSEAUX SOCIAUX",
			"Ajouter une source",
			"Fermer",
			"Type de flux",
			"Source de flux",
			"Nom de la source",
			"URL de flux",
			"Programme de flux",
			"Horaire",
			"Quotidien",
			"Hebdomadaire",
			"Nom de vue",
			"Modifier la source",
			"Êtes-vous sûr de vouloir le supprimer?",
			"Allez",
			"téléchargement groupé ",
			"Choisir le fichier",
			"Aucun fichier choisi",
			"Téléverser des flux",
			"Afficher le journal",
			"Lundi",
			"Mardi",
			"Mercredi",
			"Jeudi",
			"Vendredi",
			"Samedi",
			"Dimanche",
			"Jour",
			"Heure"
];

winlocpath = window.location.pathname.toLowerCase();
if(winlocpath.includes("/fr")){
    weblang = "fr";
    langarr = frlang;
} else {
    weblang = "en";
    langarr = enlang;
}
